[package]
name = "solc"
version = "0.0.1"
description = "Solidity compiler bindings for Rust"
license = "MIT"
edition = "2024"

[dependencies]
serde = { version = "1.0", features = ["derive"] } # json handling
serde_json = "1.0"                                 # json handling
